"멤버  시퀀스 / 테이블 / SNS 테이블 삭제"
DROP SEQUENCE MMH_MEMBER_SEQ;
DROP TABLE MMH_MEMBER CASCADE CONSTRAINTS ;
DROP TABLE MMH_MEMBER_SNS;
"멤버 시퀀스 생성"
CREATE SEQUENCE MMH_MEMBER_SEQ;

"멤버 테이블 생성"
CREATE TABLE MMH_MEMBER(
	M_NO NUMBER PRIMARY KEY,
	M_ID VARCHAR2(20) NOT NULL,
	M_PW VARCHAR2(20) NOT NULL,
	M_NAME VARCHAR2(20),
	M_EMAIL VARCHAR2(40) NOT NULL,
	M_ADDRESS VARCHAR2(200),
	M_ADDRESS2 VARCHAR2(200),
	M_JOIN CHAR(1) CHECK (M_JOIN IN('Y','N')),
	M_GRADE CHAR(1) CHECK(M_GRADE IN ('U','A')),
	M_PAYMENT CHAR(1) CHECK(M_PAYMENT IN ('Y','N'))
);
INSERT INTO MMH_MEMBER VALUES(MMH_MEMBER_SEQ.NEXTVAL, 'dada01', '1234', '다다01', 'xldksps4@naver.com', '경기도 일산동구 정발산동 1238-3', '3층', 'N', 'A', 'N');
--select * from MMH_MEMBER;

  


--MMH_MEMBER_SEQ;공유
"SNS 멤버 테이블 생성"
CREATE TABLE MMH_MEMBER_SNS(
	M_NO NUMBER PRIMARY KEY,
	M_ID VARCHAR2(20),
	M_PW VARCHAR2(20),
	M_NAME VARCHAR2(20),
	M_EMAIL VARCHAR2(40),
	M_ADDRESS VARCHAR2(200),
	M_ADDRESS2 VARCHAR2(200),
	M_JOIN CHAR(1) CHECK(M_JOIN IN('Y','N')),
	M_GRADE CHAR(1) CHECK(M_GRADE IN ('U','A')),
	M_PAYMENT CHAR(1) CHECK(M_PAYMENT IN ('Y','N'))
);

--미사용
"프로젝트 시퀀스 / 테이블 제거"
DROP SEQUENCE MMH_PROJECT_MAIN_SEQ;
DROP SEQUENCE MMH_PROJECT_SEQ;
DROP TABLE MMH_PROJECT_MAIN CASCADE CONSTRAINTS;

--미사용
"프로젝트 시퀀스 생성"
CREATE SEQUENCE MMH_PROJECT_MAIN_SEQ;
CREATE SEQUENCE MMH_PROJECT_SEQ;

--미사용
"프로젝트 테이블 생성"
CREATE TABLE MMH_PROJECT_MAIN(
	O_P_NO NUMBER PRIMARY KEY,
	P_M_NO NUMBER,
	P_M_ID VARCHAR2(20) NOT NULL,
	P_START_DATE DATE,
	P_END_DATE DATE,
);

select * from MMH_PROJECT_MAIN;
--INSERT INTO MMH_PROJECT_MAIN VALUES(450, 450, 'TEST0005', 'N', '2020-03-24', '2020-05-20', 'abcdef');

--미사용
"관리자 시퀀스 / 테이블 삭제"
DROP SEQUENCE MMH_ADMIN_SEQ;
DROP TABLE MMH_ADMIN;
--미사용
"유저 프로젝트 그룹 테이블 삭제"
DROP TABLE MMH_PROJECT_GROUP;
--미사용
"유저 프로젝트 그룹 테이블 생성"
CREATE TABLE MMH_PROJECT_GROUP(
	O_P_NO NUMBER REFERENCES MMH_PROJECT_MAIN(O_P_NO),
	M_NO NUMBER REFERENCES MMH_MEMBER(M_NO)
);

--SELECT * FROM MMH_PROJECT_GROUP;
"게시판 시퀀스 / 테이블 삭제"
DROP SEQUENCE MMH_NOTE_SEQ;

DROP TABLE MMH_NOTE;

"유저 게시판 시퀀스"
CREATE SEQUENCE MMH_NOTE_SEQ
MINVALUE 1 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 1 NOCACHE;
"관리자 게시판 시퀀스"
CREATE SEQUENCE MMH_NOTE_SEQ_AD
MINVALUE 100000000 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 100000000 NOCACHE;
--O_P_NO, N_NO, N_TITLE, N_WRITER, N_CONTENT, N_TODAY, N_IMG_PATH
"게시판(글작성페이지,공지사항)"
CREATE TABLE MMH_NOTE(
	O_P_NO NUMBER,
	N_NO NUMBER PRIMARY KEY,
	N_TITLE VARCHAR2(200),
	N_WRITER VARCHAR2(50),
	N_CONTENT VARCHAR2(4000),
	N_TODAY DATE,
	N_IMG_PATH LONG
);
--N_IMG_PATH_RES는 컬럼 추가 불가 (사유 : LONG타입은 테이블당 하나만 존재 가능)

INSERT INTO MMH_NOTE VALUES(1, MMH_NOTE_SEQ.NEXTVAL, '제목2입니다', '작성자(ID입니다)', '내용 2번', SYSDATE, NULL);
SELECT * FROM MMH_NOTE;

INSERT INTO MMH_NOTE (O_P_NO, N_NO, N_TITLE, N_WRITER, N_CONTENT, N_TODAY, N_IMG_PATH)
VALUES((SELECT M_NO FROM MMH_MEMBER WHERE M_NO=1), MMH_NOTE_SEQ.NEXTVAL, '야옹이입니다.', '네코', '야옹야옹야아옹', TO_DATE(SYSDATE, 'YYYY-MM-DD'), NULL) 
  



--미사용
"피드백 테이블 삭제"
DROP TABLE MMH_FEEDBACK;
--미사용
"피드백 테이블 생성"
CREATE TABLE MMH_FEEDBACK(
	O_P_NO NUMBER REFERENCES MMH_PROJECT_MAIN(O_P_NO),
	FE_R_NAME VARCHAR2(100),
	FE_R_PATH VARCHAR2(1000)
);
--미사용
"이미지 or PDF 테이블 삭제"
DROP TABLE MMH_IMG_OR_PDF;
--미사용
"이미지 or PDF 테이블 생성"
CREATE TABLE MMH_IMG_OR_PDF(
	O_P_NO REFERENCES MMH_PROJECT_MAIN(O_P_NO),
	IMG_NAME VARCHAR2(100),
	IMG_PATH VARCHAR2(1000)
);
--미사용
"음성인식 테이블 삭제"
DROP TABLE MMH_RECORD;
--미사용
"음성인식 테이블 생성"
CREATE TABLE MMH_RECORD(
	O_P_NO REFERENCES MMH_PROJECT_MAIN(O_P_NO),
	RE_NAME VARCHAR2(100),
	RE_PATH VARCHAR2(1000),
	RE_CONTENT VARCHAR2(4000),
	RE_TRANS_CONTENT VARCHAR2(4000)
);

--달력
"달력시퀀스"
CREATE SEQUENCE MMH_CAL_SEQ;
"달력테이블"
CREATE TABLE MMH_CAL(
	CAL_NO NUMBER PRIMARY KEY,
	CAL_TITLE VARCHAR2(100),
	CAL_CONTENT VARCHAR2(1000),
	CAL_REG_DATE DATE,
	CAL_START_DATE DATE,
	CAL_END_DATE DATE
);

SELECT M_NO FROM MMH_MEMBER WHERE M_ID='dada01';
 SELECT * FROM tab;

